### ISSUE TITLE
More explanation needed

### ISSUE THREAD

**Issue by xperiandri** [slaveOftime/Fun.Blazor#1]
As I understand it packs Bolero into Blazor WASM or Blazor Server. Am I correct?
Explanation of difference to plain Bolero would be helpful.

**Comment by albertwoo** [comment]
This is just a thin wraper of bolero. The core is the FunBlazorNode which will be finally converted to bolero node.
For example if you created a simple component like:
```fsharp
let count = html.text "hello world"
```
Then you want to use it in your existing bolero application like this:
```fsharp
let app =
    Bolero.Html.div [] [
        html.toBolero count      
    ]
```

I made this is just for trying to:

1. integrate Feliz.Engine into bolero to have a nicer DSL,
2. make a third party blazor binding generator to generate type safe DSL for bolero. Because use third party blazor libraries in bolero is very painful for me. You can check this PR: https://github.com/fsbolero/Bolero/issues/142

I also provided some helper functions, like html.inject, html.watch, html.route etc. For more information please check the docs. Or check the Fun.Blazor.Docs.WASM to check how it actually integrated with bolero.
