### ISSUE TITLE
Full Docs

### ISSUE THREAD

**Issue by AngelMunoz** [slaveOftime/Fun.Blazor#18]
Hey there, I know this might be a little bit boring but I will volunteer on some sections.

I think for better adoption ~~🦆s~~ docs are a must

Some of the pages I like docs are 
- https://imba.io/
- https://v3.vuejs.org/guide

I think we should be able to come up with a list similar to https://github.com/davedawkins/Sutil/issues/38 I think being in the realm of F# we can skip some of the topics presented both in the web pages and the issue there.

Thoughts?

even if we don't have a full design yet I can start writing markdown files if we can agree on a list or topics that works for this project

**Comment by albertwoo** [comment]
Yes agree. If you want to start to write some docs for it, maybe it is better to write it based on v2. I am working on a PR: https://github.com/slaveOftime/Fun.Blazor/pull/19
Currently branch V2 can be running for doc server or docs wasm. You can try and give some suggestion on it.

New DSL usage can be found on file https://github.com/slaveOftime/Fun.Blazor/blob/V2/Fun.Blazor.Docs.Server/Index.fs
Or https://github.com/slaveOftime/Fun.Blazor/blob/V2/Fun.Blazor.Docs.Wasm/App.fs

**Comment by albertwoo** [comment]
@AngelMunoz so you prefer static docs like vuejs.org or imba.io?

Because we already have docs (my English is not very well so the docs are not that readable) in server mode and wasm mode which mentioned at the top of the readme page. The MudBlazor site also use blazor to serve their docs.  I know blazor is not very suitable for docs in wasm mode. But in server mode, it serves pretty well (the startup time and seo is ok. Actually for SEO there is a bug after we are using blazor 6, but it is fixed in V2 when the release pipeline is fixed for server mode it should be ok).

Also I treat the current docs site as an experiment playground so it can be used for POC. It can also support markdown file directly. Like https://funblazor.slaveoftime.fun/cli-usage is just a markdown pge.

The current design (actually no design :)) is not very beautiful and identical. The layout and color etc. need some changes. So we can add markdown docs easier and make the UX better.

**Comment by AngelMunoz** [comment]
I chose those websites more to show what the content is and how it is laid out, I don't mind if the docs are in blazor server I think that could be a good showcase.

The ideal would be to have the docs and pages in markdown, that can help to lower the contribution barrier, just clone, edit a markdown file (or directly in github) and that's it.

> It can also support markdown file directly. Like https://funblazor.slaveoftime.fun/cli-usage is just a markdown pge.

Cool! I was not aware of that we could leverage that

**Comment by albertwoo** [comment]
I am not good at UX stuff. I mainly use MudBlazor for the docs (their docs site https://mudblazor.com/docs/overview is also looking good) without too much customize. I think [perla](https://perla-docs.web.app/#/content/index) is looking pretty cool. If you want you can pick anyone you like and refactor current docs layout as the way as you want if you have time. It would be very appreciate

The markdown support is pretty simple. I have a build.fsx at the root folder which can be used to convert markdown file to html in github action, the rest is just display the html in the page which is in https://github.com/slaveOftime/Fun.Blazor/blob/master/Fun.Blazor.Docs.Wasm/Components/SourceSection.fs. All other stuff in the docs project is just some showcase. You can delete or reshape as the way you expected.

**Comment by AngelMunoz** [comment]
Sounds good! I'll try to give it a go in the next few weeks.

> I think [perla](https://perla-docs.web.app/) is looking pretty cool

I don't think it looks that great but thanks!

**Comment by albertwoo** [comment]
Hi @AngelMunoz I finally managed to refresh the docs.
The UI is not changed very much. But the docs structure is totally changed. Now it should be very easy to add docs with live demo.

You can check this link for how to do it if you have some documents to add: https://funblazor.slaveoftime.fun/?doc=/How%20to%20Contribute

**Comment by AngelMunoz** [comment]
They look really great!

I will have to make some time to start sending out some docs because Fun.Bolero has a really nice way to work with UI state It'll take time but I will send some for sure

**Comment by albertwoo** [comment]
I will close this now, the documents are all updated. But it may contains typo or some other ugply part. But anyway, I already tried and will continue to polish in the future.
