### ISSUE TITLE
The value or constructor 'MudCard'' is not defined. 

### ISSUE THREAD

**Issue by MichielNass** [slaveOftime/Fun.Blazor#2]
When I use the sample code I get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0039	The value or constructor 'MudCard'' is not defined. Maybe you want one of the following:   MudCard   MudChart   MudCardMedia   MudCardHeader   MudCardActions	DSL	C:\Users\drbbr\source\repos\TraceOkApp\DSL\MudBlazor.fs	22	N/A

How can I resolce this?

**Comment by albertwoo** [comment]
Can you share your demo repo? Or let me know how you are using it?

**Comment by MichielNass** [comment]
Maybe I should clarify my intention. I intended to use this to persuade my C# colleague of the wonders of F#. And I do really like F# but everytime UI gets involved I seem to hit a brick wall. 

My C# colleague and I both know Blazor and like it a lot. I was hoping to rebuild our Blazor components we have in production and gradually replace them with components build in F#. 

Can this be used in such a way or is it an all or nothing situation?

**Comment by albertwoo** [comment]
You can check repo https://github.com/slaveOftime/Fun.Blazor.Samples for UseWithCSharpBlazor.

You can use it in anyway you want. Use csharp blazor component in fsharp, or use fsharp blazor component in csharp. But it has cost, because you need to write wrapper class or use Fun.Blazor.Cli to auto generate DSL for you.

If you are trying to build a big components in F#, it should worth it. But if you are just want to create basic controls like button etc. in F# and share in csharp project, it will not worth it.

But you should try the samples and evaluate some edge cases you can get with a POC to find out.

Because I believe there is no production use for this project, and it kind of new. So you should evaluate carefully. But I will try to make it as better as possible. You can think this project as a utility of [bolero project](https://github.com/fsbolero/Bolero), so if you think you can use bolero in production then this project will make it better.

And there is no hot reload for F# so far, so every time you need to start your project again after you made changes. It is in prgress and tracked in https://github.com/dotnet/fsharp/issues/11636

**Comment by MichielNass** [comment]
My colleague helped me and we downloaded the Samples zip but when we build we get this : 

Error	FS3087	The custom operation 'childContent' refers to a method which is overloaded. The implementations of custom operations may not be overloaded.	MinimalBlazorWASMApp	Fun.Blazor.Samples-main\Fun.Blazor.Samples-main\MinimalBlazorWASMAppWithMudBlazor\App.fs	13	N/A

**Comment by MichielNass** [comment]
Yes, with this fix it works, thank you!

**Comment by MichielNass** [comment]
> If you are trying to build a big components in F#, it should worth it. But if you are just want to create basic controls like button etc. in F# and share in csharp project, it will not worth it.

Don't sell this project short. I know it is early days, but I think there will come a time when type safety becomes the norm.
