### ISSUE TITLE
MudSpacer' is not NodeRenderFragment?

### ISSUE THREAD

**Issue by rabejens** [slaveOftime/Fun.Blazor#29]
I am trying to build a table, and want to put stuff into the toolbar.

Here is what I have so far:

```fsharp
    MudTable'<MyTableElement>() {
        Items state.files
        Hover true
        Striped true
        ToolBarContent [
            MudText'() {
                Typo Typo.h6
                "Cool tool bar"
            }
            MudSpacer'() // << boom!
        ]
    }
```

Where I added the comment `<< boom!`, the compiler complains:

```
The type 'MudSpacer'' is not compatible with type 'NodeRenderFragment'
```

How do I correctly use `MudSpacer`?

**Comment by albertwoo** [comment]
Because you are using a list to compose MudText and MudSpacer. When you call MudSpacer'() it will create a CE builder but it is not actually evaluated in fsharp so it is not NodeRenderFragment. And it is better to use below code for performance:
```fsharp
ToolBarContent (fragment {
            MudText'() {
                Typo Typo.h6
                "Cool tool bar"
            }
            MudSpacer'() // << boom!
})
```

The ToolBarContent [] is for backward compatible for vs.

**Comment by albertwoo** [comment]
Or if you prefer list, you can write like this:
```fsharp
ToolBarContent [
    MudText'() {
        Typo Typo.h6
        "Cool tool bar"
    }
    MudSpacer'.create() // << boom!
]
```
