### ISSUE TITLE
How to set RowsPerPage in MudTablePager?

### ISSUE THREAD

**Issue by rabejens** [slaveOftime/Fun.Blazor#30]
In my table, I want to use the pagination feature. I am trying to set it up like so:

```fsharp
        PagerContent(fragment {
            MudTablePager'() {
                RowsPerPage(state.page.pageSize)
                RowsPerPageChanged(SetPageSize >> dispatch)
            }
        })
```

However, I am getting
```
'RowsPerPage' is not used correctly. This is a custom operation in this query or computation expression.
```

And likewise for `RowsPerPageChanged`.

`state.page.pageSize` is of type `int` which is the `Int32` MudBlazor expects, and `SetPageSize >> dispatch` is of type `int -> unit`.

How do I have to use it?

As I understand as per the MudBlazor docs, the table is meant to have a list of all elements in memory and do the pagination in the browser. I am, however, using pagination on the server side, I submit the request to my service which gives me the respective excerpt from the data. Since we might end up with thousands of elements, this is the only feasible way to do here.

**Comment by albertwoo** [comment]
1. The error is expected, because RowsPerPage does not belong to MudTablePager', instead it belongs to MudTable'. That is why you can get the intellicense. (I think fsharp team really should improve CE intellicense).
2. According to MudBlazor doc, you are not using it correctly. MudTablePager' is just for configuration, it is not supposed to used to trigger page. MudBlazor support server side pagination and client side. But server side does not work well for elmish.
3. I noticed that you write code like "PagerContent(fragment { ...". The fragment is used to compose multiple child nodes, so if you have only one node you do not need that. You can just write "PagerContent(MudTablePager'(){...})"
4. We can only use client side pagination, but instead of using MudTablePager', we can use MudPagination' instead, or create your own pagination control. Like below example:

```fsharp

type Foo = { Name: string; Age: int }

type Model =
    {
        TotalCount: int
        Page: int
        PageSize: int
        Rows: Foo list
    }

type Msg = | LoadData of page: int


let init () =
    { TotalCount = 1000; Page = 1; PageSize = 10; Rows = [] }, Cmd.ofMsg (LoadData 1)


let update msg (model: Model) =
    match msg with
    | LoadData p ->
        { model with
            Page = p
            Rows = [ for i in 1 .. model.PageSize -> { Name = $"name {p + i}"; Age = p + i } ]
        },
        Cmd.none


let view (model: Model) (dispatch: Msg -> unit) =
    MudTable'() {
        Items model.Rows
        HeaderContent(
            fragment {
                MudTh'() { "Name" }
                MudTh'() { "Age" }
            }
        )
        RowTemplate(fun row ->
            fragment {
                MudTd'() { row.Name }
                MudTd'() { row.Age }
            }
        )
        PagerContent(
            MudPagination'() {
                Count(model.TotalCount / model.PageSize)
                Selected model.Page
                SelectedChanged(LoadData >> dispatch)
                ControlButtonClicked(
                    function
                    | Page.First -> dispatch (LoadData 1)
                    | Page.Last -> dispatch (LoadData(model.TotalCount / model.PageSize))
                    | Page.Next -> dispatch (LoadData(model.Page + 1))
                    | Page.Previous -> dispatch (LoadData(model.Page - 1))
                    | _ -> dispatch (LoadData 1)
                )
            }
        )
    }


let mudPageElmishDemo = html.elmish (init, update, view)
```
