### ISSUE TITLE
Programatic navigation

### ISSUE THREAD

**Issue by AngelMunoz** [slaveOftime/Fun.Blazor#8]
Is there a way to leverage giraffe routing style and also navigate programatically?

right now I do something like this
```fsharp
  let private navigateToRoute
    (title: IStore<string>)
    (nav: NavigationManager)
    (listId: string)
    =
    title.Publish $"{listId} | Mandadin"
    nav.NavigateTo($"/lists/{listId}")

  let private navigateToLists
    (title: IStore<string>)
    (nav: NavigationManager)
    _
    =
    title.Publish $"{getGreeting ()} | Mandadin"
    nav.NavigateTo("/")
```

but I think that's not an ideal solution specially if I want to go back I'd need to previously know.

I was thinking that perhaps adding a private module with a navigation stack/store in [this file](https://github.com/slaveOftime/Fun.Blazor/blob/master/Fun.Blazor/DslRouting.fs) and adding an entry each time the navigation changes and with the help of the navigation manager just do the last bits of navigation, it is just a random idea though

**Comment by albertwoo** [comment]
I think goback can be done with invoke the browser existing feature. Also your recommendation looks very useful. Because we do not need to invoke js.

I may need to add label for this kind of "random idea" and check it again in the future😊

**Comment by albertwoo** [comment]
DslRouting.fs is not a good place for this purpose because it may be used multiple times in application.
But it should be very simple for user to implment it. **NavigationManager** is a service provided by blazor itself. People can just create a stack object and call NavigationManager.LocationChanged.Subscribe at the begining of their application. Then you got all the needed information.

So I will close this for now. If in the future we see more use cases like this we can have a build in support for this. 😎
